name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: flask-app
      REGISTRY: docker.io
      NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
      KUBECONFIG: $HOME/.kube/config

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t $REGISTRY/$NAMESPACE/$IMAGE_NAME:latest .
        docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME:latest

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $KUBECONFIG

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout status deployment/flask-app-deployment
        kubectl get pods -l app=flask-app
